#!/bin/bash

source lib.sh


# file names & paths
DATE=`date '+%Y%m%d'`
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" 
IMAGE_DIR="icons"
TEMPLATE_FILE="template.desktop"
LAUNCHERS=("EPaath" "Wikipedia" "Kolibri" "PhET")
DATASET="dataset.json"
DST="/usr/share/applications"
ICON_DST="/usr/share/icons"
log notice  "Creating launchers"


for launcher in "${LAUNCHERS[@]}"
do 
  echo "Creating launcher for $launcher"
  [ -f "${launcher}".desktop ] && rm "${launcher}".desktop
  cp "${TEMPLATE_FILE}" "${launcher}".desktop
  sed -i "s@{{NAME}}@$(jq -r ".launcher.${launcher}.NAME" $DATASET)@g" "${launcher}".desktop
  sed -i "s@{{DESCRIPTION}}@$(jq -r ".launcher.${launcher}.DESCRIPTION" $DATASET)@g" "${launcher}".desktop
  sed -i "s@{{CATAGORY}}@$(jq -r ".launcher.${launcher}.CATAGORY" $DATASET)@g" "${launcher}".desktop
  sed -i "s@{{ICON}}@$(jq -r ".launcher.${launcher}.ICON" $DATASET)@g" "${launcher}".desktop
  sed -i "s@{{COMMAND}}@$(jq -r ".launcher.${launcher}.COMMAND" $DATASET)@g" "${launcher}".desktop
  mv "${launcher}".desktop "${DST}"
  cp -r ./"${IMAGE_DIR}"/*.png "${ICON_DST}"
done


log notice  "Done!!  Creating launchers"
