#!/bin/bash

source lib.sh
curl -o kolibri -L http://pantry.learningequality.org/downloads/kolibri/v0.12.1/kolibri-0.12.1.pex
mv kolibri /usr/local/bin/

cp -r config/kolibri.service /usr/lib/systemd/system/
mkdir -p /home/pi/.kolibri

sytemctl start kolibri.service
sytemctl enable kolibri.service


log notice "Installed kolibri"
