#!/bin/bash



#Variables declare


DOWNLOAD_FILE="https://download.olenepal.org/epaath-new.tar.gz"

mkdir -p /tmp/epaath/

if [ ! -f epaath-new.tar.gz ]; then
	rm -rf /tmp/epaath && mkdir -p /tmp/epaath
    wget "$DOWNLOAD_FILE" 
    tar -xf epaath-new.tar.gz -C /tmp/epaath/
fi


if [ -f /var/www/html/index.html ]; then 
    rm -f /var/www/html/index.html 
fi

mv /tmp/epaath /var/www/html/

chmod -R 775 /var/www
chown -R www-data:www-data /var/www

